const mockMentions = [
  // Twitter mentions
  {
    id: 1,
    platform: "Twitter",
    author: "@techie_sarah",
    text: "Just tried {{BRAND}}'s new product and I'm absolutely blown away! The quality is incredible and customer support was so helpful. Highly recommend! #impressed",
    timestamp: "2026-02-25T10:32:00Z",
    url: "#",
    likes: 142,
    shares: 38,
  },
  {
    id: 2,
    platform: "Twitter",
    author: "@frustrated_user99",
    text: "{{BRAND}} your app keeps crashing every time I try to check out. Lost my cart 3 times now. This is unacceptable and I'm moving to a competitor if this isn't fixed ASAP.",
    timestamp: "2026-02-25T09:15:00Z",
    url: "#",
    likes: 87,
    shares: 22,
  },
  {
    id: 3,
    platform: "Twitter",
    author: "@daily_shopper",
    text: "Has anyone used {{BRAND}} before? Thinking of switching from my current provider. Any thoughts?",
    timestamp: "2026-02-25T08:45:00Z",
    url: "#",
    likes: 12,
    shares: 3,
  },
  {
    id: 4,
    platform: "Twitter",
    author: "@marketwatcher",
    text: "{{BRAND}} just announced Q4 earnings. Numbers look solid but stock still taking a hit. Interesting market dynamics.",
    timestamp: "2026-02-24T22:10:00Z",
    url: "#",
    likes: 56,
    shares: 19,
  },
  {
    id: 5,
    platform: "Twitter",
    author: "@loyalcustomer_jen",
    text: "Been a {{BRAND}} customer for 5 years. Every year they get better. New update is chef's kiss!",
    timestamp: "2026-02-24T20:05:00Z",
    url: "#",
    likes: 203,
    shares: 67,
  },
  // Reddit mentions
  {
    id: 6,
    platform: "Reddit",
    author: "u/honest_reviewer",
    text: "Genuine review of {{BRAND}} after 6 months of use: The product is good but pricing has gotten out of hand. Used to be great value. Their customer service team is still top notch though.",
    timestamp: "2026-02-25T07:30:00Z",
    url: "#",
    likes: 1240,
    shares: 0,
  },
  {
    id: 7,
    platform: "Reddit",
    author: "u/techcomparison",
    text: "Comparing {{BRAND}} vs competitors — {{BRAND}} wins on UI/UX but loses on pricing. Full comparison in comments.",
    timestamp: "2026-02-24T18:00:00Z",
    url: "#",
    likes: 876,
    shares: 0,
  },
  {
    id: 8,
    platform: "Reddit",
    author: "u/angry_ex_customer",
    text: "{{BRAND}} refused to honor their warranty claim. I have everything in writing and they still denied it. Filing a complaint with the BBB. Anyone else had this issue?",
    timestamp: "2026-02-24T15:45:00Z",
    url: "#",
    likes: 2103,
    shares: 0,
  },
  {
    id: 9,
    platform: "Reddit",
    author: "u/deal_hunter_pro",
    text: "PSA: {{BRAND}} is running a 40% off sale this weekend only. Great time to grab their premium plan!",
    timestamp: "2026-02-24T12:00:00Z",
    url: "#",
    likes: 3400,
    shares: 0,
  },
  // News mentions
  {
    id: 10,
    platform: "News",
    author: "TechCrunch",
    text: "{{BRAND}} Raises $50M Series B to Expand Global Operations — The company plans to double its engineering team and enter three new markets in 2026.",
    timestamp: "2026-02-25T06:00:00Z",
    url: "#",
    likes: 0,
    shares: 540,
  },
  {
    id: 11,
    platform: "News",
    author: "Forbes",
    text: "{{BRAND}} Named One of the Best Workplaces of 2026 — Employees praise the company culture, benefits, and leadership transparency.",
    timestamp: "2026-02-24T09:00:00Z",
    url: "#",
    likes: 0,
    shares: 230,
  },
  {
    id: 12,
    platform: "News",
    author: "Business Insider",
    text: "Is {{BRAND}} losing its edge? A deep dive into customer churn data and what the company must do to stay competitive in 2026.",
    timestamp: "2026-02-23T14:30:00Z",
    url: "#",
    likes: 0,
    shares: 180,
  },
  // Instagram mentions
  {
    id: 13,
    platform: "Instagram",
    author: "@lifestyle_with_maya",
    text: "Obsessed with everything {{BRAND}} right now. This has completely transformed my morning routine! Use my code MAYA20 for 20% off. #ad #{{BRAND}}partner",
    timestamp: "2026-02-25T11:00:00Z",
    url: "#",
    likes: 8920,
    shares: 340,
  },
  {
    id: 14,
    platform: "Instagram",
    author: "@real_talk_reviews",
    text: "Honest take: {{BRAND}}'s packaging is beautiful but the product itself is just average for the price point. Save your money.",
    timestamp: "2026-02-24T17:20:00Z",
    url: "#",
    likes: 4210,
    shares: 120,
  },
  // LinkedIn mentions
  {
    id: 15,
    platform: "LinkedIn",
    author: "James Whitfield, VP Marketing",
    text: "Thrilled to announce our partnership with {{BRAND}}! Their enterprise solutions have streamlined our operations by 40%. Excited to see what we build together.",
    timestamp: "2026-02-25T08:00:00Z",
    url: "#",
    likes: 445,
    shares: 78,
  },
  {
    id: 16,
    platform: "LinkedIn",
    author: "Elena Torres, Industry Analyst",
    text: "{{BRAND}}'s latest product release signals a clear pivot toward the enterprise segment. Smart move, but they risk alienating their SMB base. Thoughts?",
    timestamp: "2026-02-24T11:00:00Z",
    url: "#",
    likes: 312,
    shares: 45,
  },
];

const responseTemplates = {
  negative_complaint: {
    category: "Complaint / Negative",
    urgency: "High",
    tone: "Empathetic & Proactive",
    templates: [
      "Hi [Name], we're so sorry to hear about this experience — it's not the standard we hold ourselves to. Please DM us your order/account details and we'll make this right immediately.",
      "Thank you for flagging this, [Name]. We take every concern seriously. Could you please reach out to our support team at support@brand.com? A senior agent will personally handle your case.",
      "We sincerely apologize for the inconvenience, [Name]. We'd love to resolve this for you right away. Can you share more details so we can investigate?",
    ],
    doList: [
      "Respond within 1 hour",
      "Acknowledge the issue without making excuses",
      "Offer a direct resolution path (DM, email, phone)",
      "Follow up after resolution",
    ],
    dontList: [
      "Don't be defensive",
      "Don't use generic copy-paste responses",
      "Don't delete the comment/post",
      "Don't escalate publicly",
    ],
  },
  positive_praise: {
    category: "Praise / Positive",
    urgency: "Low",
    tone: "Warm & Grateful",
    templates: [
      "This made our day, [Name]! Thank you so much for the kind words — feedback like yours keeps our team motivated. Hope to keep exceeding your expectations!",
      "Wow, thank you [Name]! We're so glad you're loving it. Mind if we share your feedback with our team? It means the world to us!",
      "You're amazing, [Name]! We work hard to deliver exactly this. Thank you for being such a wonderful customer — have you tried [related product]? We think you'd love it too!",
    ],
    doList: [
      "Like and respond promptly",
      "Be personal and authentic",
      "Consider reposting/sharing UGC (with permission)",
      "Nurture the relationship",
    ],
    dontList: [
      "Don't ignore positive mentions",
      "Don't use robotic responses",
      "Don't immediately upsell",
    ],
  },
  neutral_question: {
    category: "Question / Inquiry",
    urgency: "Medium",
    tone: "Helpful & Informative",
    templates: [
      "Great question, [Name]! [Answer to question]. Feel free to DM us if you have more questions — we're always happy to help!",
      "Hi [Name], thanks for reaching out! [Relevant info]. You can also find detailed info at our help center: [link]. Let us know if there's anything else we can help with!",
      "Hey [Name]! [Answer]. Hope that helps — don't hesitate to reach out if you need more info. We're here for you!",
    ],
    doList: [
      "Answer promptly and accurately",
      "Link to relevant resources",
      "Invite further engagement",
      "Tag the right team if needed",
    ],
    dontList: [
      "Don't leave questions unanswered",
      "Don't give incorrect information",
      "Don't be dismissive",
    ],
  },
  neutral_discussion: {
    category: "Discussion / Analysis",
    urgency: "Low",
    tone: "Transparent & Engaging",
    templates: [
      "Thanks for the thoughtful analysis, [Name]! We're always listening to community feedback. [Address specific point]. We'd love to hear more of your thoughts!",
      "Great points, [Name]. Transparency is important to us — [provide relevant context or data]. What would you like to see from us going forward?",
      "Hi [Name], we appreciate the balanced perspective. [Acknowledge valid points]. We're continuously working on [improvement area] and would love your input!",
    ],
    doList: [
      "Engage thoughtfully",
      "Provide data or context where appropriate",
      "Acknowledge both strengths and areas for improvement",
    ],
    dontList: [
      "Don't be defensive about criticism",
      "Don't oversell",
      "Don't ignore nuanced feedback",
    ],
  },
};

module.exports = { mockMentions, responseTemplates };
